.github/CODEOWNERS

feat : 리뷰어 풀스택 팀으로 설정

---

.gitignore
build.gradle
src/main/java/com/akatsuki/newsum/common/dto/ApiResponse.java
src/main/java/com/akatsuki/newsum/common/dto/ErrorCodeAndMessage.java
src/main/java/com/akatsuki/newsum/common/dto/ErrorResponse.java
src/main/java/com/akatsuki/newsum/common/dto/ResponseCodeAndMessage.java
src/main/java/com/akatsuki/newsum/common/exception/ApplicationException.java
src/main/java/com/akatsuki/newsum/common/exception/GlobalExceptionHandler.java
src/main/java/com/akatsuki/newsum/common/exception/UnauthorizedException.java
src/main/java/com/akatsuki/newsum/common/security/JwtTokenUtil.java
src/main/java/com/akatsuki/newsum/common/security/TokenProvider.java
src/main/java/com/akatsuki/newsum/config/QueryDslConfig.java
src/main/java/com/akatsuki/newsum/config/SecurityConfig.java
src/main/java/com/akatsuki/newsum/config/SwaggerConfig.java
src/main/java/com/akatsuki/newsum/domain/webtoon/controller/WebtoonController.java
src/main/java/com/akatsuki/newsum/domain/webtoon/dto/AiAuthorInfoDto.java
src/main/java/com/akatsuki/newsum/domain/webtoon/dto/WebtoonCardDto.java
src/main/java/com/akatsuki/newsum/domain/webtoon/dto/WebtoonDetailResponse.java
src/main/java/com/akatsuki/newsum/domain/webtoon/dto/WebtoonResponse.java
src/main/java/com/akatsuki/newsum/domain/webtoon/dto/WebtoonSlideDto.java
src/main/java/com/akatsuki/newsum/domain/webtoon/dto/WebtoonSourceDto.java
src/main/java/com/akatsuki/newsum/domain/webtoon/entity/webtoon/Webtoon.java
src/main/java/com/akatsuki/newsum/domain/webtoon/exception/WebtoonNotFoundException.java
src/main/java/com/akatsuki/newsum/domain/webtoon/repository/WebtoonDetailRepository.java
src/main/java/com/akatsuki/newsum/domain/webtoon/repository/WebtoonQueryRepository.java
src/main/java/com/akatsuki/newsum/domain/webtoon/repository/WebtoonQueryRepositoryImpl.java
src/main/java/com/akatsuki/newsum/domain/webtoon/repository/WebtoonRepository.java
src/main/java/com/akatsuki/newsum/domain/webtoon/service/WebtoonService.java
src/test/java/com/akatsuki/newsum/NewsumApplicationTests.java

#24 
#25 
- /api/v1/webtoons/{webtoonId} 추가
- /api/v1/webtoons/{webtoonId}/details 추가
- 기초 응답 객체 추가
- 기초 예외 처리 핸들러 추가
>

Feat/24 : 웹툰 기본 정보/상세 정보 조회 api 구현

---

src/main/java/com/akatsuki/newsum/common/dto/ResponseCodeAndMessage.java
src/main/java/com/akatsuki/newsum/config/SecurityConfig.java
src/main/java/com/akatsuki/newsum/converter/DateConverter.java
src/main/java/com/akatsuki/newsum/domain/user/controller/UserController.java
src/main/java/com/akatsuki/newsum/domain/user/dto/RecentViewWebtoonListResponse.java
src/main/java/com/akatsuki/newsum/domain/user/service/UserService.java
src/main/java/com/akatsuki/newsum/domain/webtoon/entity/webtoon/RecentView.java
src/main/java/com/akatsuki/newsum/domain/webtoon/repository/WebtoonQueryRepository.java
src/main/java/com/akatsuki/newsum/domain/webtoon/repository/WebtoonQueryRepositoryImpl.java

#37 
- 최근 본 웹툰 목록 조회 API 추가
- 명세서 반영
>

Feat/37 : 최근 본 웹툰 목록 조회 API 추가

---

src/main/java/com/akatsuki/newsum/config/SecurityConfig.java

feat : CORS 보안 정책 제거

---

src/main/java/com/akatsuki/newsum/domain/webtoon/controller/CommentController.java

 fix : 댓글 회원 연동

---

.env.example
src/main/resources/application-local.yml

fix : 서버 포트 주입받도록 수정

---

src/main/java/com/akatsuki/newsum/domain/webtoon/controller/CommentController.java

fix : access-token UserID 파싱 로직 변경

---

src/main/resources/application.yml

feat : add http11 log

---

src/main/java/com/akatsuki/newsum/common/dto/ResponseCodeAndMessage.java
src/main/java/com/akatsuki/newsum/common/security/UserDetailsImpl.java
src/main/java/com/akatsuki/newsum/config/WebMvcConfig.java
src/main/java/com/akatsuki/newsum/domain/webtoon/controller/WebtoonController.java
src/main/java/com/akatsuki/newsum/domain/webtoon/repository/RecentViewQueryRepository.java
src/main/java/com/akatsuki/newsum/domain/webtoon/repository/RecentViewQueryRepositoryImpl.java
src/main/java/com/akatsuki/newsum/domain/webtoon/repository/RecentViewRepository.java
src/main/java/com/akatsuki/newsum/domain/webtoon/service/WebtoonService.java

Feat/27 : 통합 서빙 에러 수정(로그인)

---

src/main/java/com/akatsuki/newsum/domain/webtoon/entity/webtoon/Webtoon.java
src/main/resources/db/migration/V3__Alter_table_webtoon_title.sql

fix : 웹툰 타이틀 데이터베이스 varchar(100)설정

---

src/main/java/com/akatsuki/newsum/config/WebMvcConfig.java

fix : ViewController React Routing경로 추가

---

src/main/java/com/akatsuki/newsum/domain/webtoon/controller/WebtoonController.java
src/main/java/com/akatsuki/newsum/domain/webtoon/entity/webtoon/RecentView.java
src/main/java/com/akatsuki/newsum/domain/webtoon/entity/webtoon/Webtoon.java
src/main/java/com/akatsuki/newsum/domain/webtoon/repository/RecentViewRepository.java
src/main/java/com/akatsuki/newsum/domain/webtoon/service/WebtoonService.java

fix : 조회수 증가 로직 및 최근 본웹툰 추가 로직 추가

---

.github/workflows/backend.yml

GitHub Actions - CI 구축 #40
백앤드 ci/cd 파이프라인 구축

[BE]GitHub Actions run test

---

.github/workflows/backend.yml

90 backendyml 생성

---

.github/workflows/backend.yml

[BE]GitHub Actions run test update

---

.github/workflows/backend.yml

[BE]GitHub Actions run without test

---

.github/workflows/backend.yml

[BE]GitHub Actions run infisical export

---

.github/workflows/backend.yml

infisical 환경변수 주입

---

.github/workflows/backend.yml

불필요한 빌드과정 수정

---

.github/workflows/backend.yml

불필요한 빌드과정 재수정

---

.github/workflows/backend.yml

CI CD 과정 분리1

---

.github/workflows/backend.yml

CI CD 분리 빌드는 중복

---

.github/workflows/backend.yml

[재] 환경병수 주입

---

.github/workflows/backend.yml

[재] 환경병수 주입 수정

---

.github/workflows/backend.yml

[재] 환경병수 주입 수정2

---

.github/workflows/backend.yml

[재] 환경병수 주입 수정3

---

.github/workflows/backend.yml

[재] 환경병수 주입 수정4

---

.github/workflows/backend.yml

[재] 환경병수 주입 수정 .env파일

---

.github/workflows/backend.yml

Github Actions run test1

---

.github/workflows/backend.yml

Github Actions run test2

---

.github/workflows/backend.yml

Github Actions run 마지막

---

.github/workflows/backend.yml

Github Actions run last test

---

.github/workflows/backend.yml

Github Actions run lastlast test

---

.github/workflows/backend.yml

Github Actions run syntax fix

---

.github/workflows/backend.yml

Github Actions run syntax fix3

---

.github/workflows/backend.yml

Github Actions run syntax fix5

---

.github/workflows/backend.yml

Github Actions run syntax fix6

---

.github/workflows/backend.yml

Github Actions run syntax fix7

---

.github/workflows/backend.yml

Github Actions run syntax fix8

---

.github/workflows/backend.yml

Github Actions run syntax fix9

---

.github/workflows/backend.yml

Github Actions run syntax fix10

---

src/main/java/com/akatsuki/newsum/common/pagination/deserializer/CreatedAtIdCursorDeserializer.java
src/main/java/com/akatsuki/newsum/domain/webtoon/repository/WebtoonFavoriteRepositoryImpl.java

#174 
Cusor 가져오는 년도 2100 로 설정되어 있어, gt 조건이기 때문에 값을 못가져옴
북마크 webtoonFavorite.createdAt > (cursor.getCreatedAt())) 로 수정 
-
감사합니다.

[#174] Cusor 관련 기능 오류 개선

---

src/main/resources/application-dev.yml
src/main/resources/application-local.yml
src/main/resources/application-prod.yml
src/main/resources/application.yml

fix : application.yml 환경변수 dev,prod 재설정

---

.github/workflows/be-dev-cd.yml

ci : 환경변수 적용

---

src/main/java/com/akatsuki/newsum/common/dto/ResponseCodeAndMessage.java
src/main/java/com/akatsuki/newsum/common/pagination/query/builder/NotificationPageQueryBuilder.java
src/main/java/com/akatsuki/newsum/domain/notification/application/NotificationService.java
src/main/java/com/akatsuki/newsum/domain/notification/application/NotificationUseCase.java
src/main/java/com/akatsuki/newsum/domain/notification/application/dto/NotificationPageListCommand.java
src/main/java/com/akatsuki/newsum/domain/notification/application/dto/NotificationPageListResult.java
src/main/java/com/akatsuki/newsum/domain/notification/domain/Notification.java
src/main/java/com/akatsuki/newsum/domain/notification/domain/NotificationType.java
src/main/java/com/akatsuki/newsum/domain/notification/infrastructure/persistence/NotificationRepository.java
src/main/java/com/akatsuki/newsum/domain/notification/infrastructure/persistence/NotificationRepositoryImpl.java
src/main/java/com/akatsuki/newsum/domain/notification/infrastructure/persistence/dto/NotificationReadModel.java
src/main/java/com/akatsuki/newsum/domain/notification/infrastructure/persistence/jpa/NotificationJpaRepository.java
src/main/java/com/akatsuki/newsum/domain/notification/infrastructure/persistence/jpa/NotificationQueryRepository.java
src/main/java/com/akatsuki/newsum/domain/notification/infrastructure/persistence/jpa/NotificationQueryRepositoryImpl.java
src/main/java/com/akatsuki/newsum/domain/notification/presentation/api/NotificationController.java
src/main/java/com/akatsuki/newsum/domain/notification/presentation/dto/NotificationListPageResponse.java
src/main/java/com/akatsuki/newsum/domain/notification/presentation/dto/NotificationResult.java
src/main/resources/db/migration/V2025.05.29.1__Create_Notification_Table.sql

#134 
- 알림 테이블 엔티티 추가
- 알림 테이블 생성 DDL문 추가
- 알림 PageQueryBulder 추가
- 알림 조회 API 추가

Feat/lookup notifications #134

---

.github/workflows/be-dev-cd.yml
.github/workflows/be-main-cd.yml
.github/workflows/be-main-ci.yml

#178  
> dev 파이프라인에서 설정 정보를 prod 정보로 바꾸어 파이프라인을 작성했습니다.
> 기존에 하려고 했던 스모크테스트는 백엔드의 통합테스트에서 수행하기 때문에 제외하고
> E2E 테스트는 추후 도입할 예정입니다.

40 GitHub actions ci 구축

---

.github/CODEOWNERS
.github/workflows/reviewers.yml

ci : CODEOWNER파일 삭제 및 리뷰어 파이프라인 추가(클라우드 #116)

---

.github/CODEOWNERS
.github/workflows/reviewers.yml

클라우드(#116)
CODEOWNERS 파일 삭제 및 리뷰어 파이프라인 도입

Fix/116 backend 리뷰어 할당 수정

---

.github/workflows/be-dev-cd.yml
.github/workflows/be-main-cd.yml

CI 파이프라인에서 시간이 5분이상 소요될 때가 있는 것을 발견하여 최적화 작업 수행

ci : cloudfront에서 infisical cli 바이너리 파일 다운로드 받게 수정

---

src/main/java/com/akatsuki/newsum/config/OpenFeignConfig.java
src/main/java/com/akatsuki/newsum/domain/webtoon/service/ImageQueueService.java
src/main/java/com/akatsuki/newsum/extern/dto/CreateWebtoonApiRequest.java
src/main/resources/application-dev.yml
src/main/resources/application-local.yml

- 요청 형식이 맞지 않아 생기는 문제를 해결했습니다.(422에러)
- String이 아닌 List<Map<String,Obejct>>형식으로 변경했습니다.

Fix: 웹툰 생성 로직 요청 422 에러 수정

---

src/main/java/com/akatsuki/newsum/domain/webtoon/controller/WebtoonController.java
src/main/java/com/akatsuki/newsum/domain/webtoon/entity/webtoon/ImageGenerationQueue.java
src/main/java/com/akatsuki/newsum/domain/webtoon/service/WebtoonService.java

Fix: 이미지 생성 간 큐 상태값 변경

---

src/main/resources/application.yml

feat: 프로메테우스 설정관련 Spring Actuator 설정

---

src/main/java/com/akatsuki/newsum/job/NotificationJob.java
src/main/java/com/akatsuki/newsum/job/WebtoonCreateJob.java

- 알림 삭제 로직 주기 변경
- 이미지 생성 로직 주기 변경

Fix: 스케쥴 로직 시간 변경

---

.github/workflows/be-dev-cd.yml

cicd : aws dev 환경 파이프라인 작성

---

.github/workflows/be-dev-cd.yml

cicd : ec2 private ip 가져와지는지 확인

---

.github/workflows/be-dev-cd.yml

cicd : 엔터가 아닌 띄어쓰기로 IP 가져오기

---

.github/workflows/be-dev-cd.yml

cicd : secrets 사용하던 값들 다 변수화

---

.github/workflows/be-dev-cd.yml

cicd : 환경변수 삭제 주석처리

---

.github/workflows/be-dev-cd.yml

cicd : 환경변수 안가져와지는 문제

---

.github/workflows/be-dev-cd.yml

cicd : dotenv format 변경

---

.github/workflows/be-dev-cd.yml

cicd : 환경변수 확인 후 제거 로직 부활

---

.github/workflows/be-dev-cd.yml

cicd : builx 경로 설정 후 github actions에서 찾을 수 있게 설정

---

build.gradle
src/main/java/com/akatsuki/newsum/common/enums/EnumString.java
src/main/java/com/akatsuki/newsum/domain/notification/application/dto/NotificationTypeString.java
src/main/java/com/akatsuki/newsum/domain/webtoon/entity/webtoon/ImageGenerationQueue.java
src/main/java/com/akatsuki/newsum/domain/webtoon/entity/webtoon/NewsSource.java
src/main/java/com/akatsuki/newsum/domain/webtoon/entity/webtoon/Webtoon.java
src/main/java/com/akatsuki/newsum/domain/webtoon/enums/CategoryString.java
src/main/java/com/akatsuki/newsum/domain/webtoon/service/WebtoonService.java
src/main/java/com/akatsuki/newsum/extern/dto/ImageGenerationApiRequest.java
src/test/java/com/akatsuki/newsum/archunit/EnumUsageRuleTest.java

#256 
enum String 기능 추가  및 웹툰 뉴스보고서 링크 보이도록 수정했습니다.

[Fix] #256 enum String 기능 추가  및 웹툰 뉴스보고서 링크 보이도록 수정

---

src/main/resources/application-dev.yml
src/main/resources/application.yml

[chore] kafka yml 수정

---

docker-compose.yml
src/main/java/com/akatsuki/newsum/sse/controller/SseController.java
src/main/java/com/akatsuki/newsum/sse/repository/WebtoonSseEmitterRepository.java
src/main/java/com/akatsuki/newsum/sse/service/SseService.java
src/main/resources/application-dev.yml
src/main/resources/application.yml

#264  카프카에서 사용자가 페이지를 나갔을 경우, leave api 로 신호를 줍니다.
#264

[Fix] # 264 kafka connect 설정 수정

---

src/main/java/com/akatsuki/newsum/sse/kafka/ViewerCountBroadcaster.java
src/main/java/com/akatsuki/newsum/sse/kafka/WebtoonViewerEventPublisher.java

[chore]  #269 카프카 메세지 전송 log 추가

---

.github/workflows/be-dev-cd.yml

cicd : ssh 경로 출력

---

src/main/java/com/akatsuki/newsum/config/RedisCacheConfig.java
src/main/resources/db/migration/V2025.07.08.1__Create_webtoon_at_partial_index.sql

275/ Postgresql 인덱스 추가

---

src/main/java/com/akatsuki/newsum/config/RedisCacheConfig.java
src/main/java/com/akatsuki/newsum/domain/webtoon/repository/WebtoonRepository.java
src/main/java/com/akatsuki/newsum/domain/webtoon/service/WebtoonService.java
src/main/resources/application-dev.yml
src/main/resources/application-local.yml
src/main/resources/application.yml

#279 
cpu 사용률 이슈로 인한 코드 개선 및 캐시 튜닝

[ref]279 cpu 사용률 개선

---

src/main/java/com/akatsuki/newsum/cache/ViewerEventDeduplicationCache.java
src/main/java/com/akatsuki/newsum/config/RedisCacheConfig.java
src/main/java/com/akatsuki/newsum/config/cache/JitterRedisCache.java
src/main/java/com/akatsuki/newsum/config/cache/JitterRedisCacheManager.java
src/main/resources/application-local.yml

[Refactor] Jitter 캐시전략 도입

---

src/main/java/com/akatsuki/newsum/common/dto/ResponseCodeAndMessage.java
src/main/java/com/akatsuki/newsum/domain/webtoon/controller/WebtoonController.java
src/main/java/com/akatsuki/newsum/log/dto/WebtoonViewLogRequest.java
src/main/java/com/akatsuki/newsum/log/entity/WebtoonViewLog.java
src/main/java/com/akatsuki/newsum/log/repository/WebtoonViewLogRepository.java
src/main/java/com/akatsuki/newsum/log/service/WebtoonViewLogService.java
src/main/resources/db/migration/V2025.07.20__Create_webtoon_log_table.sql

유저들이 어떤 페이지에 들어 갔는지 수집하는 로그 테이블입니다
postgresql 에 로그인한 유저, 비로그인 유저 별로 웹툰 페이지 방문 log 데이터를 수집합니다

[Feat] 285 postgresql 유저 웹툰 시간대 별 접속 웹툰페이지 출력
